-- Migration: 004_analytics_and_insights_tables
-- Run once in Supabase SQL editor or via supabase db push.
-- Creates 4 tables for the analytics & insights layer.
-- Does NOT touch categorization tables.

-- ─────────────────────────────────────────────────────────────────
-- TABLE 1: monthly_user_summary
-- Pre-aggregated debit/credit/savings per user per calendar month.
-- Refreshed by the worker; never computed on-demand.
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS monthly_user_summary (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL,
    month               DATE NOT NULL,          -- always 1st of the month
    total_debit         NUMERIC DEFAULT 0,
    total_credit        NUMERIC DEFAULT 0,
    net_savings         NUMERIC DEFAULT 0,
    total_transactions  INTEGER DEFAULT 0,
    savings_ratio       NUMERIC DEFAULT 0,      -- net_savings / total_credit (0 if no credit)
    created_at          TIMESTAMP DEFAULT now(),
    updated_at          TIMESTAMP DEFAULT now(),
    UNIQUE (user_id, month)
);
CREATE INDEX IF NOT EXISTS idx_monthly_summary_user       ON monthly_user_summary (user_id);
CREATE INDEX IF NOT EXISTS idx_monthly_summary_user_month ON monthly_user_summary (user_id, month DESC);

CREATE OR REPLACE FUNCTION _upd_monthly_summary_ts()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS trg_monthly_summary_updated ON monthly_user_summary;
CREATE TRIGGER trg_monthly_summary_updated
    BEFORE UPDATE ON monthly_user_summary
    FOR EACH ROW EXECUTE FUNCTION _upd_monthly_summary_ts();


-- ─────────────────────────────────────────────────────────────────
-- TABLE 2: recurring_transactions
-- Detected recurring payment patterns per user / merchant.
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS recurring_transactions (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                  UUID NOT NULL,
    category_id              UUID,
    merchant_name            TEXT NOT NULL,
    avg_amount               NUMERIC,
    recurrence_interval_days INTEGER,
    next_expected_date       DATE,
    confidence_score         NUMERIC DEFAULT 0,
    last_detected_at         TIMESTAMP DEFAULT now(),
    created_at               TIMESTAMP DEFAULT now(),
    UNIQUE (user_id, merchant_name)
);
CREATE INDEX IF NOT EXISTS idx_recurring_user          ON recurring_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_recurring_user_merchant ON recurring_transactions (user_id, merchant_name);
CREATE INDEX IF NOT EXISTS idx_recurring_next_date     ON recurring_transactions (next_expected_date);


-- ─────────────────────────────────────────────────────────────────
-- TABLE 3: user_financial_risk_profile
-- One row per user; updated periodically by the worker.
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_financial_risk_profile (
    user_id                  UUID PRIMARY KEY,
    expense_volatility       NUMERIC DEFAULT 0,
    savings_ratio            NUMERIC DEFAULT 0,
    recurring_burden_ratio   NUMERIC DEFAULT 0,
    risk_score               INTEGER DEFAULT 0,    -- 0–100
    risk_level               TEXT    DEFAULT 'LOW'
        CHECK (risk_level IN ('LOW', 'MODERATE', 'HIGH')),
    last_updated             TIMESTAMP DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_risk_profile_user ON user_financial_risk_profile (user_id);


-- ─────────────────────────────────────────────────────────────────
-- TABLE 4: user_financial_insights
-- Point-in-time insight messages generated by the insights engine.
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_financial_insights (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL,
    insight_type TEXT NOT NULL,
    -- SPENDING_ALERT | EVENING_PATTERN | WEEKEND_SPIKE |
    -- SUBSCRIPTION_ALERT | SAVINGS_OPPORTUNITY
    message      TEXT NOT NULL,
    severity     TEXT DEFAULT 'INFO'
        CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    created_at   TIMESTAMP DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_insights_user         ON user_financial_insights (user_id);
CREATE INDEX IF NOT EXISTS idx_insights_user_created ON user_financial_insights (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_insights_user_type    ON user_financial_insights (user_id, insight_type);
